### PR TITLE
Allow installation outside of /usr

### PR DESCRIPTION
**Pull request by attente**

### CODE REVIEW

**Comment by lmq3342xja** [comment]
this is good ,thanks

**Review by lmq3342xja — COMMENTED** [review]
Allow installation outside of /usr/

**Review by lmq3342xja — APPROVED** [review]

**Comment by attente** [comment]
Is this project still active?

**Comment by lmq3342xja** [comment]
@attente I am still in maintenance, the address is https://github.com/lmq3342xja/fcitx-qimpanel.I have merged you codes

**Comment by lmq3342xja** [comment]
I am still in maintenance, the address is https://github.com/lmq3342xja/fcitx-qimpanel .I have merged you codes

**Comment by attente** [comment]
Ah, thank you. I'll use your repo next time.

**Pull request closed without merging**
